application: webapp2-user-authentication
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts
  
- url: /images
  static_dir: images
  
- url: /js
  static_dir: js

- url: /sass
  static_dir: sass
  
- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app
  



libraries:
- name: webapp2
  version: "2.5.1"
